# Site settings
title: Tyler C. Butler
email: tcb89@georgetown.edu
description: > # this means to ignore newlines until "baseurl:"
  Tyler Butler is a master's student at Georgetown University, pursuing an M.A. in Security Studies in the Walsh School of Foreign Service with a certificate in Eurasian, Russian and East European Studies. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tbutler.org" # the base hostname & protocol for your site
twitter_username: tbutler0x90
github_username:  tcbutler320
linkedin_username: tyler-b-a700a1aa

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
jobtitle: "Georgetown University"
jobsubtitle: "Walsh School of Foreign Service"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""